---
version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errorlint
    - gocritic
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
  settings:
    gocritic:
      enabled-checks:
        - boolExprSimplify
        - equalFold
        - hugeParam
        - indexAlloc
        - initClause
        - nestingReduce
        - ptrToRefParam
        - rangeExprCopy
        - ruleguard
        - truncateCmp
        - unnamedResult
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-naming
        - name: error-return
        - name: exported
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: var-naming
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck

formatters:
  enable:
    - goimports
