---
go:
  version: 1.23
repository:
  path: github.com/paragm/user_session_exporter
build:
  flags: -trimpath
  ldflags: |
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{.BuildUser}}
    -X github.com/prometheus/common/version.BuildDate={{.BuildDate}}
tarball:
  files:
    - LICENSE
    - NOTICE
    - examples/systemd/
